/**
 * V3 状态枚举字典
 * 基于 成员C页面设计清单 §9
 * 严格使用本字典进行状态判断和展示
 */

// 9.3 充电模式
export const CHARGE_MODE = {
  FAST: 'FAST',
  SLOW: 'SLOW',
}

export const CHARGE_MODE_TEXT = {
  [CHARGE_MODE.FAST]: '快充',
  [CHARGE_MODE.SLOW]: '慢充',
}

// 9.1 请求状态
export const REQUEST_STATUS = {
  WAITING_AREA: 'WAITING_AREA',
  QUEUED: 'QUEUED',
  CHARGING: 'CHARGING',
  COMPLETED: 'COMPLETED',
  COMPLETED_EARLY: 'COMPLETED_EARLY',
  CANCELLED: 'CANCELLED',
  FAULT_INTERRUPTED: 'FAULT_INTERRUPTED',
}

export const REQUEST_STATUS_TEXT = {
  [REQUEST_STATUS.WAITING_AREA]: '等候区等待',
  [REQUEST_STATUS.QUEUED]: '桩队列等待',
  [REQUEST_STATUS.CHARGING]: '正在充电',
  [REQUEST_STATUS.COMPLETED]: '正常完成',
  [REQUEST_STATUS.COMPLETED_EARLY]: '提前结束完成',
  [REQUEST_STATUS.CANCELLED]: '已取消',
  [REQUEST_STATUS.FAULT_INTERRUPTED]: '故障中断',
}

// 请求是否处于活跃状态（不可再次提交新请求）
export const ACTIVE_STATUSES = [
  REQUEST_STATUS.WAITING_AREA,
  REQUEST_STATUS.QUEUED,
  REQUEST_STATUS.CHARGING,
]

// 有详单的终态
export const HAS_DETAIL_STATUSES = [
  REQUEST_STATUS.COMPLETED,
  REQUEST_STATUS.COMPLETED_EARLY,
  REQUEST_STATUS.FAULT_INTERRUPTED,
]

// 9.2 充电桩状态
export const STATION_STATUS = {
  RUNNING: 'RUNNING',
  SHUTDOWN: 'SHUTDOWN',
  FAULT: 'FAULT',
}

export const STATION_STATUS_TEXT = {
  [STATION_STATUS.RUNNING]: '运行中',
  [STATION_STATUS.SHUTDOWN]: '已关闭',
  [STATION_STATUS.FAULT]: '故障',
}

// 9.4 调度模式
export const DISPATCH_MODE = {
  NORMAL: 'NORMAL',
  EXT_SINGLE_BATCH: 'EXT_SINGLE_BATCH',
  EXT_FULL_BATCH: 'EXT_FULL_BATCH',
}

export const DISPATCH_MODE_TEXT = {
  [DISPATCH_MODE.NORMAL]: '普通调度',
  [DISPATCH_MODE.EXT_SINGLE_BATCH]: '单次联合调度',
  [DISPATCH_MODE.EXT_FULL_BATCH]: '批量调度',
}

// 9.5 故障策略
export const FAULT_DISPATCH_MODE = {
  PRIORITY: 'PRIORITY',
  TIME_ORDER: 'TIME_ORDER',
}

export const FAULT_DISPATCH_MODE_TEXT = {
  [FAULT_DISPATCH_MODE.PRIORITY]: '故障队列优先',
  [FAULT_DISPATCH_MODE.TIME_ORDER]: '时间顺序重排',
}
