#!/usr/bin/env python3
"""Reset the local development database and seed deterministic accounts."""

from __future__ import annotations

import argparse
import os
import sys
import time
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = ROOT / "backend"
FRONTEND_HMR_FILE = ROOT / "frontend" / "src" / "dev-reset-signal.js"

sys.path.insert(0, str(BACKEND_DIR))

from app import create_app  # noqa: E402
from app.utils.auth import hash_password  # noqa: E402
from app.utils.db import execute_db, init_db, query_db  # noqa: E402


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Reset local DB and seed demo accounts.")
    parser.add_argument("--users", type=int, default=10, help="number of normal users to create")
    parser.add_argument("--password", default="123456", help="password used by all seeded accounts")
    parser.add_argument("--admin", default="admin", help="admin username")
    parser.add_argument("--db-path", default=None, help="override DB_PATH for this reset")
    parser.add_argument(
        "--touch-hmr",
        action="store_true",
        help="update a watched frontend file so Vite refreshes the browser",
    )
    return parser.parse_args()


def _remove_sqlite_files(db_path: Path) -> None:
    for path in [db_path, Path(f"{db_path}-journal"), Path(f"{db_path}-wal"), Path(f"{db_path}-shm")]:
        if path.exists():
            path.unlink()


def _seed_accounts(app, users: int, password: str, admin_username: str) -> None:
    with app.app_context():
        for index in range(1, users + 1):
            username = f"user{index:02d}"
            execute_db(
                """
                INSERT INTO user (user_id, username, password_hash, battery_capacity, role)
                VALUES (?, ?, ?, ?, 'USER')
                """,
                [f"U{index:03d}", username, hash_password(password), 60.0],
            )

        execute_db(
            """
            INSERT INTO user (user_id, username, password_hash, battery_capacity, role)
            VALUES (?, ?, ?, ?, 'ADMIN')
            """,
            [f"U{users + 1:03d}", admin_username, hash_password(password), 80.0],
        )


def _touch_hmr_file() -> None:
    FRONTEND_HMR_FILE.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_HMR_FILE.write_text(
        "// Auto-generated by scripts/reset_dev_db.py.\n"
        f"export const DEV_RESET_STAMP = {int(time.time() * 1000)}\n",
        encoding="utf-8",
    )


def main() -> int:
    args = _parse_args()
    if args.users < 1:
        raise SystemExit("--users must be >= 1")

    if args.db_path:
        os.environ["DB_PATH"] = str(Path(args.db_path).expanduser().resolve())

    app = create_app(os.environ.get("FLASK_CONFIG", "development"))
    db_path = Path(app.config["DATABASE_PATH"]).expanduser().resolve()

    _remove_sqlite_files(db_path)
    init_db(app)
    _seed_accounts(app, args.users, args.password, args.admin)

    with app.app_context():
        total_users = query_db("SELECT COUNT(*) AS cnt FROM user", one=True)["cnt"]
        station_count = query_db("SELECT COUNT(*) AS cnt FROM charging_station", one=True)["cnt"]

    if args.touch_hmr:
        _touch_hmr_file()

    print(f"Database reset: {db_path}")
    print(f"Seeded accounts: {total_users} users total, {station_count} stations")
    print(f"Admin: {args.admin} / {args.password}")
    print(f"Users: user01..user{args.users:02d} / {args.password}")
    if args.touch_hmr:
        print(f"Vite HMR touched: {FRONTEND_HMR_FILE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
